### ISSUE TITLE
is underscore a valid ID character? 

### ISSUE THREAD

**Issue by mgottein** [audiobahn404/test_cs352#10]
Is the regex for ID (letter)(letter|digit)*

https://github.com/audiobahn404/test_cs352/blob/master/tests/syntax/test_object_fields_in_expressions

**Comment by faultyserver** [comment]
Piazza post 47 states that underscores are valid as long as they are not the first character (emphasis mine):

> ... the following will be sufficient: starts with a letter (either case), after which it can contain letters (either case), numbers, **or underscores**. 

This implies a regex like `[a-zA-Z][a-zA-Z0-9_]*`.
