### ISSUE TITLE
"Violations Stress Test"

### ISSUE THREAD

**Issue by AGoel1** [audiobahn404/test_cs352#12]
Expcted output
Line 3, type violation
undefined
Line 5, type violation
Line 8, b has no value
Line 10, type violation
Line 10, type violation

However, we are not supposed to print a newline after we print out undefined.

Therefore, I think the expected should be
Line 3, type violation
undefinedLine 5, type violation
Line 8, b has no value
Line 10, type violation
Line 10, type violation

**Comment by AGoel1** [comment]
The TA also said that undefined from a document.write statement should not produce a Newline. I read the README saying that violations have their own newline, I assume that only holds for 
runtime and type violations

**Comment by faultyserver** [comment]
From Piazza post 176:

> No, you are not required to do the extra book keeping to have an optional newline in front of an error message.

and from 172:

> For most of the test cases it won't matter.  It's looking like I'll have to do the ones that do manually, and accept anything reasonable.
> ...
> We didn't specify closely enough, so I'll have to take both.

I'm marking this as a won't fix (but not closing), as I personally prefer the separate lines for output, and users can easily go in and remove them if they feel like it.

**Comment by faultyserver** [comment]
I also brought this up in #11, so I'm marking as duplicate as well.

**Comment by AGoel1** [comment]
Sounds good

**Comment by faultyserver** [comment]
The TAs just confirmed that both forms will be accepted in Piazza post 176:

> As what you have done is more work, I'll accept it for this part.  for anyone else reading this, please don't do these conditional newlines.  For part 3, we have tightened up the rules.

So, for part 3, things might change. I'll leave this open until then.

**Comment by faultyserver** [comment]
So, part 3 entirely changes how the output of a program is going to be tested. All errors will be a single line sent _specifically_ to STDERR in the form of:

```
Line x, <error_text>\n
```

All other output goes _specifically_ to STDOUT.

There are a few changes I'm going to need to make to the script itself to handle this update. Once they are all implemented, this issue will be closed.

**Comment by audiobahn404** [comment]
# 6.1 `.`
