### ISSUE TITLE
test_do_while_with_complex_condition

### ISSUE THREAD

**Issue by alecgorge** [audiobahn404/test_cs352#17]
```
<script type="text/JavaScript">
var a = false;
do {
}
while(true && 1 + 4 < 2 * 2 || a == false);
</script>
```

Won't `a` always equal `false` and cause this to infinite loop?

**Comment by faultyserver** [comment]
Looking at it, yes. But it didn't in my code. Does it loop for you?

**Comment by alecgorge** [comment]
Yes, both `test_do_while_with_complex_condition` and `test_while_with_complex_condition` loop infinitely for me. I just changed the declaration to `var a = true`.

They also infinite loop in js as well for what it is worth.

Thanks so much for putting the great spec and tests together! It really makes me feel more comfortable about the project

**Comment by faultyserver** [comment]
Sounds and looks good. I'll merge in your fixes in a second.
