### ISSUE TITLE
test_undefined_value_in_do_while

### ISSUE THREAD

**Issue by alecgorge** [audiobahn404/test_cs352#18]
```
<script type="text/JavaScript">
var a = 1 + "str"
do {
}
while(a);
</script>
```

I believe the condition unknown error should occur on line 5, not line 3. I'm guessing this is an artifact of copy and paste from the equivalent while loop test case.

I would apply the appropriate labels but it won't let me (not a contributor I guess)

**Comment by faultyserver** [comment]
Closed by c139e38df67d
