### ISSUE TITLE
grammar/objects/declaration/err_test_blank_with_linebreak

### ISSUE THREAD

**Issue by alecgorge** [audiobahn404/test_cs352#4]
I don't think that this should fail. It seems valid to me based on the spec.

**Comment by faultyserver** [comment]
Page 2 of the spec says:

> To declare an object without initializing its values, we can write in the following form:
> var person = { }
> In the above, white spaces are allowed between the braces, but not line breaks.

Unless there was more discussion on Piazza, I interpret the spec to say that this is invalid.

**Comment by alecgorge** [comment]
Ah, I see now. I was focusing this part with the assumption the no field was the "last field":

> The last field may or may not be followed by line breaks before the closing “}”.

You are correct.
