### ISSUE TITLE
When "<br />" is a substring, a newline is printed. Should be printed exactly as read.

### ISSUE THREAD

**Issue by mlenarto** [audiobahn404/test_cs352#7]

**Comment by faultyserver** [comment]
Can you elaborate on this? I don't have any test cases where `<br />` is a _substring_, though the [newline concatenation test](https://github.com/audiobahn404/test_cs352/blob/d5251291124be89a1d27a0ee76695f0ac3cbf799/tests/semantics/test_write_newline_formed_by_concatenation) might be what you are referencing.

If so, look at the referenced post on Piazza (124). It says:

> If after concatenation the parameter becomes `<br />` for print, then I would think this is equivalent to the situation quoted from the spec "When the interpreter sees `<br />` (in its exact form) as a parameter in document.write statement, or a variable that has the string value `<br />`, the semantic action must print a newline, i.e. `\n` in the C statement.".
> 
> In other words, since a+b now holds the exact form of `<br />`, document.write would print a newline.

**Comment by mlenarto** [comment]
Shoot! My mistake! I apologize, I was misinterpreting one of the tests.
There is no issue.

**Comment by faultyserver** [comment]
That's alright, it's what this section is for!

It wasn't ever explicitly stated in the spec, and it took me about 20 minutes to go dig this up when I wrote the test.
